export const English = {
    Hello: "Hello",
    Fish: "Fish",
    Time: "Time",
    Picture: "Picture",
    Description: "Description",
    Weight: "Weight",
    Length: "Length",
    Bait: "Bait",
    Lure: "Lure",
    Location: "Location",
    SubmitPost: "Submit Catch Post",
    ConfirmDelete: "Confirm Delete",
    CancelDelete: "Cancel Delete",
    Cancel: "Cancel",
    ShareYourCatch: "Share Your Catch",
    EditYourCatch: "Update Your Catch",
    SubmitUpdate: "Update Catch Post",
    Required: "Required",
    DeleteCatchPost: "Delete Catch Post",
    TheCatch: "The Catch",
    Conditions: "Conditions",
    Temperature: "Temperature",
    Cloud: "Cloud",
    Humidity: "Humidity",
    Precipitation: "Precipitation",
    Pressure: "Pressure",
    Wind: "Wind",
    Dicussion: "Discusson",
    CommentsQuestions: "Comments / Questions",
    Posts: "Posts",
    AddToTheDiscussion: "Add to the Discussion",
    WhatYouWantToSay: "What you want to say...",
    Submit: "Submit",
    Edit: "Edit",
    SubmitEdit: "Submit Edit",
    DeletePost: "Delete Post",
    About: "About",
    GlobalFeed: "Global Feed",
    ShareCatch: "Share a Catch",
    MyCatches: "My Catches",
    RecentGlobalHeading: "Recent Catches Across World",
    Logout: "Logout",
    ShareNewCatch: "Share a New Catch",
    ShowDetails: "Show Details",
    UpdateDetails: "Update Details",
    Login: "Login",
    SignUp: "Sign Up",
    SearchCatchesInYourArea: "Search for catches in your area...",
    SplashMain: "Fishing is about much more than fish.",
    SplashLine2: "It's about the simplicity, the community, and yes,",
    SplashLine3: " the whoppers are bitin', and find your next trophy catch.",
    SplashLine2Emphasis: "the boasting",
    SplashLine3Emphasis: "See where",
    Email: "Email",
    Password:  "Password",
    DemoUser: "Demo User",
    DontHaveAccount: "Don’t have an account?",
    AlreadyHaveAccount: "Already have an account?",
    NoThanks: "No Thanks",
    Username: "Username",
    RepeatPassword: "Repeat Password",
    Submit: "Submit",
    SignUp: "Sign Up",
    SearchCatchesArea: "Search for catches in your area...",
    SearchAnArea: "Search for catches in another area...",
    RecentCatchesLocality: "Recent Catches in Locality",
    Filters: "Filters",
    FishQuery: "Search Text in Name",
    Min: "Min",
    Max: "Max",
    NoResults: "Sadly, no one is sharing their catches here. Why not be the first?",
    TypeOfFish: "Type of Fish",
    pounds: "lbs",
    inches: "inches",
}

export const Chinese = {
    Hello: "你好!",
    Fish: "鱼",
    Description: "描述",
    Time: "时间",
    Picture: "图片",
    Weight: "重量",
    Length: "长度",
    Bait: "诱饵",
    Lure: "鱼饵",
    Location: "位置",
    SubmitPost: "提交帖子",
    ConfirmDelete: "确认删除",
    CancelDelete: "取消删除",
    Cancel: "取消",
    ShareYourCatch: "分享你的收获",
    EditYourCatch: "编辑你的捕获",
    SubmitUpdate: "提交更新",
    Required: "必填",
    DeleteCatchPost: "删除捕获帖子",
    TheCatch: "鱼钩",
    Conditions: "条件",
    Temperature: "温度",
    Cloud: "云",
    Humidity: "湿度",
    Precipitation: "降水",
    Pressure: "压力",
    Wind: "风",
    Dicussion: "讨论",
    CommentsQuestions: "评论/问题",
    Posts: "帖子",
    AddToTheDiscussion: "加入讨论",
    WhatYouWantToSay: "你想说什么....",
    Submit: "提交",
    Edit: "编辑",
    SubmitEdit: "提交编辑",
    DeletePost: "删除帖子",
    About: "关于",
    GlobalFeed: "全球饲料",
    ShareCatch: "分享渔获",
    MyCatches: "我的鱼狗",
    RecentGlobalHeading: "世界各地最近的鱼钩",
    Logout: "注销",
    ShareNewCatch: "分享新渔获",
    ShowDetails: "显示详情",
    UpdateDetails: "更新详情",
    Login: "登录",
    SignUp: "注册",
    SearchCatchesInYourArea: "搜索您所在地区的渔获物...",
    SplashMain: "钓鱼不仅仅是鱼.",
    SplashLine2: "这是关于简单，社区，是的，",
    SplashLine2Emphasis: "吹嘘",
    SplashLine3: "巨无霸在哪里咬，然后找到你的下一个奖杯.",
    SplashLine3Emphasis: "看看",
    Email: "电子邮件",
    Password:  "密码",
    DemoUser: "演示用户",
    DontHaveAccount: "没有帐户？",
    AlreadyHaveAccount: "已经有一个帐户?",
    NoThanks: "不要，谢谢",
    Username: "用户名",
    RepeatPassword: "重复输入密码",
    Submit: "提交",
    SignUp: "报名",
    SearchCatchesArea: "搜索您所在地区的渔获物...",
    SearchAnArea: "搜索其他区域的渔获物...",
    RecentCatchesLocality: "当地最近的渔获物",
    Filters: "过滤器",
    FishQuery: "在名称中搜索文本",
    Min: "最小",
    Max: "最大",
    NoResults: "可悲的是，没有人在这里分享他们的渔获。为什么不成为第一？",
    TypeOfFish: "鱼的种类",
    pounds: "英磅",
    inches: "英寸",
}