"""“message”

Revision ID: 090fa93097d0
Revises: 0c1c1fffc935
Create Date: 2022-07-10 14:58:07.760323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '090fa93097d0'
down_revision = '0c1c1fffc935'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catches', sa.Column('catch_time', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('catches', 'catch_time')
    # ### end Alembic commands ###
